### ISSUE TITLE
Figure out why the server is crashing

### ISSUE THREAD

**Issue by RadicalZephyr** [RadicalZephyr/http-server#3]
After running for ~10 seconds or so the server crashes.  Unclear what's going on.

```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(ArrayList.java:653)
    at java.util.ArrayList.get(ArrayList.java:429)
    at net.zephyrizing.http_server.HttpProtocol.requestFromLines(HttpProtocol.java:16)
    at net.zephyrizing.http_server.HttpConnectionImpl.getRequest(HttpConnectionImpl.java:34)
    at net.zephyrizing.http_server.HttpServer.serve(HttpServer.java:78)
    at net.zephyrizing.http_server.HttpServer.main(HttpServer.java:45)
```

**Comment by RadicalZephyr** [comment]
Something about the parsing of certain requests (probably sent by chrome) was failing.  This was fixed by making the parsing more robust and error tolerant, and making the server simply ignore malformed requests.
